### ISSUE TITLE
[FEATURE REQUEST] keep opening the tmp file in a loop until all dest files are satisfied

### ISSUE THREAD

**Issue by elundmark** [thameera/vimv#10]
I edited my personal copy to do this, using a while loop and breaking whenever the src and dest are the same or the dest already exists. This seems to me to be the expected behaviour.
I have a copy of it here: https://gist.github.com/elundmark/bf1e3fc925aa8d8472ea449e4f6766f2

**Comment by thameera** [comment]
Hey @elundmark, can you please explain a bit more about what you meant by "until all dest files are satisfied". 
Does that prompt the user until all files are renamed (so you can't keep any file with the old name)?

**Comment by elundmark** [comment]
I thought more about this, and I might have gone too far in thinking that this is expected by anyone but me.
For me it made sense to keep opening the tmp file in the editor until every file was moved successfully, i.e. every file had a new filename.
I realize now this might not be for everybody, most people _would_ expect to be able to not give it any new name at all, and it exiting normally.
I myself have always expected the opposite when bulk-renaming.
I'll close this, thanks for the code though! Finally got me to switch from Thunar's Bulk-Rename tool :+1:
