### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by n1ck3** [thameera/vimv#11]
Hi,

I really like vimv, but had to hack it to work with py3. It works for me but I think might like py3 compatibility as well.

Cheers!

**Comment by thameera** [comment]
What part is failing for you with Python 3? The script uses purely shell commands and does not depend on Python.

**Comment by n1ck3** [comment]
I am terribly sorry.

I made this comment in the wrong repo. I was using https://github.com/ivanmaeder/vimv and had your this repo's page up and didn't realize it was the wrong one.

Sorry for the confusion. Closing this ticket.
