### ISSUE TITLE
Does not honor $TMPDIR (PR included)

### ISSUE THREAD

**Issue by jkurei** [thameera/vimv#13]
vimv assumes `/tmp` as the temporary directory. It isn't the case on some systems, like Android's [Termux](https://termux.com/) (actually, this is probably Android's fault and not Termux', come to think of it). 

`$TMPDIR` is a commonly used variable to indicate where the temporary directory is in this system, or may be what directory the user wants you to use ([Wikipedia](https://en.wikipedia.org/wiki/TMPDIR), [Ubuntu's Wiki](https://help.ubuntu.com/community/EnvironmentVariables)).

On the other hand, you can't just use TMPDIR without a default, because some other systems don't set it, like Ubuntu on WSL. I that case I suggest vimv should go on using /tmp, which is the most common and actually what Ubuntu on WSL uses.

Here is a PR: https://github.com/thameera/vimv/pull/12 

PD: By the way, I love vimv and use it every day, thanks!

**Comment by thameera** [comment]
Thanks! Definitely a useful addition. Merged the PR.
