### ISSUE TITLE
Opens with Nano instead of Vim

### ISSUE THREAD

**Issue by canada-water** [thameera/vimv#25]
I'm not sure what the problem is, but whenever I open vimv, it opens with Nano instead of Vim. I can use Nano no problem, but it's just a bit of an annoyance when Vim has so much more functionality, and when this is supposed to open Vim.

**Comment by Rom1deTroyes** [comment]
As said in the description :

> - If you have an $EDITOR environment variable set, vimv will use its value by default.

So maybe you have this variable set ?
You can check this by running `echo $EDITOR` or `env | grep EDITOR`

**Comment by thameera** [comment]
Setting the `$EDITOR` variable correctly should work. This might help: https://unix.stackexchange.com/questions/73484/how-can-i-set-vi-as-my-default-editor-in-unix
